@baseUrl = http://127.0.0.1/api/v1/orderitems
@cType = application/json
@password = password


### ROUTE API CUSTOMERS

### Get all order items
get {{baseUrl}}
token: {{password}}

### Create a new order item
POST {{baseUrl}}
Authorization:  {{password}}
Content-Type: {{cType}}

{
    "order_id": 2,
    "product_id": 1,
    "quantity": 5
}

### Update order item by ID
PUT {{baseUrl}}/2
Authorization: {{password}}
Content-Type: {{cType}}

{
    "order_id": 2,
    "product_id": 2,
    "quantity": 10
}

### Get order item by ID
GET {{baseUrl}}/3
Authorization: {{password}}
Content-Type: {{cType}}

### Delete an order item
DELETE {{baseUrl}}/2
Authorization: {{password}}
Content-Type: {{cType}}

### Show data join
GET {{baseUrl}}
Authorization: {{password}}
Content-Type: {{cType}}

### Show data join by ID
GET {{baseUrl}}/2
Authorization: {{password}}
Content-Type: {{cType}}