@baseUrl = http://127.0.0.1/api/v1/payment
@cType = application/json
@password = password

### ROUTE API PAYMENT

### get request payment
get {{baseUrl}}
token: {{password}}

### INI BUAT GET DATA payment BY ID
post {{baseUrl}}
Authorization:  {{password}}
Content-Type: {{cType}}

### post request payment
post {{baseUrl}}
Authorization:  {{password}}
Content-Type: {{cType}}

{
    "order_id": "3",
    "gross_amount": "8000",
    "first_name": "Fatwa",
    "last_name": "Arriva",
    "email": "Arriva@example.com",
    "phone": "081249013294"
}

### put request payment by ID
put {{baseUrl}}
Authorization: {{password}}
Content-Type: {{cType}}

{
    "order_id": "1",
    "gross_amount": "1000",
    "first_name": "Fatwa",
    "last_name": "Arriva",
    "email": "Arriva@example.com",
    "transaction_status": "success",
    "phone": "081249013294"
}

### delete request payment by ID
delete {{baseUrl}}
Authorization: {{password}}
Content-Type: {{cType}}